name: GitHub Classroom Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Check if students copied files to src
        run: |
          echo "Checking src directory contents..."
          if [ -z "$(ls -A src/*.py 2>/dev/null)" ]; then
            echo "❌ ERROR: No Python files found in src/ directory!"
            echo "Did you forget to copy the template files?"
            echo "Run: cp template/*.py src/"
            exit 1
          fi
          echo "✅ Found Python files in src/:"
          ls -la src/*.py
      
      - name: Run tests with grading script
        run: |
          python run_tests.py
        continue-on-error: true
      
      - name: Autograding Reporter
        uses: education/autograding@v1
        if: always()